# Generated by Django 4.2 on 2023-08-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_of_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
